# -*- coding: utf-8 -*-
"""finalproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eT7_HVwZKFSzV-cYjA7izNO1ZP5vPsRW
"""

# pip install kagglehub[pandas-datasets]
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset (pass file name as positional arg)
df = pd.read_csv("data.csv")

df =  pd.DataFrame(df)

df.head()

pd.options.display.float_format = '{:,.2f}'.format

# Before We Proceed For better understand we go add  devide price by 1000000 to be 'price_M'  data analysis concern.
df['price_m'] =  df['price']/1000000

df.head()

"""1. Data Cleaning & Understanding"""

# Missing Values
print(df.isnull().sum())

(df['price']==0).sum()

df=df[df['price']>0]

(df['price']==0).sum()

# Outliers
numeric_df=df.select_dtypes(include=["int64","float64"])

plt.figure(figsize=(15,10))
for i,col in enumerate(numeric_df.columns):
    plt.subplot(4,5,i+1)
    sns.boxplot(y=df[col])
    plt.title(col)

plt.tight_layout()
plt.show()

df_cleaned=df.copy()

for col in numeric_df.columns:
    Q1=df_cleaned[col].quantile(0.25)
    Q3=df_cleaned[col].quantile(0.75)
    IQR=Q3-Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    df_cleaned = df_cleaned[(df_cleaned[col] >= lower_bound) & (df_cleaned[col] <= upper_bound)]

print(f"Original dataset shape: {df.shape}")
print(f"Cleaned dataset shape: {df_cleaned.shape}")

# lets check outliers again
numeric_df=df_cleaned.select_dtypes(include=["int64","float64"])

plt.figure(figsize=(15,10))
for i,col in enumerate(numeric_df.columns):
    plt.subplot(4,5,i+1)
    sns.boxplot(y=df_cleaned[col])
    plt.title(col)

plt.tight_layout()
plt.show()

"""Data Visualization"""

plt.figure(figsize=(12,8))
sns.histplot(df["price"],bins=50,kde=True)
plt.title("Distribution of Price")
plt.show()

numerical_cols=df.select_dtypes(include=["float64","int64"])
corr_matrix=numerical_cols.corr()

plt.figure(figsize=(14,8))
sns.heatmap(corr_matrix,annot=True,fmt=".2f",cmap="viridis")
plt.title("Correlation Matrix")
plt.show()

import warnings
warnings.filterwarnings("ignore")

features=["sqft_living","bedrooms","bathrooms"]

plt.figure(figsize=(18,10))
for i,feature in enumerate(features):
    plt.subplot(2,2,i+1)
    sns.scatterplot(x=df[feature], y=df["price"], alpha=0.4)

    mean_data=df.groupby(feature)["price"].mean().reset_index()
    sns.lineplot(x=mean_data[feature],y=mean_data["price"],color="red",label="Mean Price")

    plt.title(f"Price vs {feature}")
    plt.legend()

plt.tight_layout()
plt.show()

features=["bathrooms","bedrooms","city","condition"]

plt.figure(figsize=(12,8))
for i,feature in enumerate(features):
    plt.subplot(2,2,i+1)
    sns.countplot(x=feature,data=df)
    plt.title(f'Count of {feature}')
    plt.xticks(rotation=90)

plt.tight_layout()
plt.show()

df.columns

df.groupby('statezip')['price'].mean().sort_values(ascending=False)

df.groupby('statezip')['price'].count()

df.groupby('waterfront')['price'].mean()

categorical_cols=["waterfront","view","condition","city"]
for col in categorical_cols:
    print(f"\nUnique values in '{col}': {df[col].nunique()}")
    print(df[col].value_counts())

df.groupby('city')['price'].count()

"""cluster"""

features = [
    'bedrooms',
    'bathrooms',
    'sqft_living',
    'sqft_lot',
    'floors',
    'waterfront',
    'view',
    'condition',
    'sqft_above',
    'sqft_basement',
    'yr_built'
]

df.dtypes

from sklearn.preprocessing import StandardScaler

X = df[features]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

inertia = []

for k in range(1, 11):
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)

plt.plot(range(1, 11), inertia)
plt.xlabel('Number of Clusters')
plt.ylabel('Inertia')
plt.show()

kmeans = KMeans(n_clusters=4, random_state=42)
df['cluster'] = kmeans.fit_predict(X_scaled)

df.groupby('cluster')[features].mean()

df.groupby('cluster')['price'].mean()

cluster_names = {
    0: 'Upper-Middle',
    1: 'Mid-Range',
    2: 'Budget',
    3: 'Luxury'
}

df['cluster_label'] = df['cluster'].map(cluster_names)

"""classification"""

features_cls = [
    'bedrooms',
    'bathrooms',
    'sqft_living',
    'sqft_lot',
    'floors',
    'waterfront',
    'view',
    'condition',
    'sqft_above',
    'sqft_basement',
    'yr_built'
]

x = df[features_cls]
y = df['cluster']

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

gb_model = GradientBoostingClassifier(random_state=42)
gb_model.fit(x_train, y_train)
y_pred = gb_model.predict(x_test)

test_acc = accuracy_score(y_test, y_pred)

print("Test Accuracy:", round(test_acc, 4))

from sklearn.metrics import confusion_matrix, classification_report

best_model = GradientBoostingClassifier()
best_model.fit(x_train_scaled, y_train)
y_pred = best_model.predict(x_test_scaled)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

from sklearn.model_selection import cross_val_score

scores = cross_val_score(best_model, x_train_scaled, y_train, cv=5)

print("Cross Validation Accuracy:", scores.mean())

"""regression"""

print(x_train.shape)
print(x_test.shape)

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

df = df_cleaned.copy()

df['date'] = pd.to_datetime(df['date'])
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day

df = pd.get_dummies(df, columns=['street', 'city', 'statezip', 'country'], drop_first=True)

x = df.drop(['price', 'date','price_m'], axis=1)
y = df['price']

num_cols = ['bedrooms','bathrooms','sqft_living','sqft_lot','floors',
            'waterfront','view','condition','sqft_above','sqft_basement',
            'yr_built','yr_renovated','year','month','day']

scaler = StandardScaler()
x[num_cols] = scaler.fit_transform(x[num_cols])

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score

xgb_model = XGBRegressor(n_estimators=100, random_state=42, verbosity=0)

xgb_model.fit(x_train, y_train)

y_train_pred = xgb_model.predict(x_train)
y_test_pred = xgb_model.predict(x_test)


y_pred = xgb_model.predict(x_test)
mse = mean_squared_error(y_test, y_pred)
rmse = mse ** 0.5
r2 = r2_score(y_test, y_pred)


rmse_train = mean_squared_error(y_train, y_train_pred) ** 0.5
rmse_test = mean_squared_error(y_test, y_test_pred) ** 0.5

r2_train = r2_score(y_train, y_train_pred)
r2_test = r2_score(y_test, y_test_pred)

print("XGBoost Regressor Performance:")
print(f"  RMSE: {rmse:.2f}")
print(f"  R2 Score: {r2:.2f}")
print(f"  RMSE (Train): {rmse_train:.2f}")
print(f"  RMSE (Test) : {rmse_test:.2f}")
print(f"  R2 Score (Train): {r2_train:.4f}")
print(f"  R2 Score (Test) : {r2_test:.4f}")

model_columns = x_train.columns



#pip install openai streamlit

import os
from openai import OpenAI


client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

def get_llm_explanation(price, category, bedrooms, bathrooms, sqft_living, waterfront):
    prompt = f"""
    A house price prediction system produced the following results:

    Predicted Price: {price:.2f} USD
    Category: {category}

    Features:
    Bedrooms: {bedrooms}
    Bathrooms: {bathrooms}
    Living Area: {sqft_living} sqft
    Waterfront: {waterfront}

    Explain professionally:
    1. Why this house received this price prediction.
    2. Why it was classified as {category}.
    3. Whether the price seems reasonable based on the features.
    """

    response = client.chat.completions.create(
        model="gpt-4",  # أو gpt-3.5-turbo حسب حسابك
        messages=[{"role": "user", "content": prompt}],
        temperature=0.3
    )

    return response.choices[0].message.content
    # ------------------------------
# Streamlit App
# ------------------------------
import streamlit as st

st.title("🏡 House Price Prediction & Explanation")
st.write("Predict house price and get a professional explanation using LLM.")

# Sidebar Inputs
st.sidebar.header("House Features")

bedrooms = st.sidebar.number_input("Bedrooms", 1, 20, 3)
bathrooms = st.sidebar.number_input("Bathrooms", 1, 10, 2)
sqft_living = st.sidebar.number_input("Living Area (sqft)", 100, 20000, 1500)
sqft_lot = st.sidebar.number_input("Lot Area (sqft)", 500, 100000, 5000)
floors = st.sidebar.number_input("Floors", 1, 5, 1)

waterfront = st.sidebar.selectbox("Waterfront", [0, 1])
view = st.sidebar.slider("View (0-4)", 0, 4, 0)
condition = st.sidebar.slider("Condition (1-5)", 1, 5, 3)

sqft_above = st.sidebar.number_input("Sqft Above Ground", 100, 20000, 1200)
sqft_basement = st.sidebar.number_input("Sqft Basement", 0, 10000, 300)

yr_built = st.sidebar.number_input("Year Built", 1900, 2026, 2000)
yr_renovated = st.sidebar.number_input("Year Renovated (0 if none)", 0, 2026, 0)

year = st.sidebar.number_input("Sale Year", 2000, 2026, 2014)
month = st.sidebar.slider("Sale Month", 1, 12, 6)
day = st.sidebar.slider("Sale Day", 1, 31, 15)
# Simple category based on grade
# Create input dataframe
input_features = pd.DataFrame({
    'bedrooms':[bedrooms],
    'bathrooms':[bathrooms],
    'sqft_living':[sqft_living],
    'sqft_lot':[sqft_lot],
    'floors':[floors],
    'waterfront':[waterfront],
    'view':[view],
    'condition':[condition],
    'sqft_above':[sqft_above],
    'sqft_basement':[sqft_basement],
    'yr_built':[yr_built],
    'yr_renovated':[yr_renovated],
    'year':[year],
    'month':[month],
    'day':[day]
})

# أضف الأعمدة الناقصة (dummy columns)
for col in model_columns:
    if col not in input_features.columns:
        input_features[col] = 0

# نفس ترتيب الأعمدة
input_features = input_features[model_columns]

# Scaling
input_features[num_cols] = scaler.transform(input_features[num_cols])

# Prediction
pred_price = float(xgb_model.predict(input_features)[0])

# Category based on predicted price
category = "High" if pred_price > 500000 else "Low"

# Handle missing dummy columns (if needed)



st.subheader(f"Predicted Price: ${pred_price:,.2f}")
st.write(f"Category: **{category} Price**")

# Button to get LLM explanation
if st.button("Get LLM Explanation"):
    explanation = get_llm_explanation(
    pred_price,
    category,
    bedrooms,
    bathrooms,
    sqft_living,
    waterfront
)
    st.markdown("### 💡 Explanation")
    st.write(explanation)
